//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProDetail
    {
        public int ProID { get; set; }
        public string ColorName { get; set; }
        public string RGB { get; set; }
        public string Size { get; set; }
        public double Price { get; set; }
        public string ProDecription { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
