//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProID { get; set; }
        public string ProName { get; set; }
        public int CatID { get; set; }
        public string ProImage { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ProDetail ProDetail { get; set; }
    }
}
